// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_VRH_PQvBnTVsJAEI4Vox095ixJKy44g',
    appId: '1:381796812762:web:71787e5fa70f93caea62e3',
    messagingSenderId: '381796812762',
    projectId: 'new-project-f0523',
    authDomain: 'new-project-f0523.firebaseapp.com',
    databaseURL: 'https://new-project-f0523-default-rtdb.firebaseio.com',
    storageBucket: 'new-project-f0523.appspot.com',
    measurementId: 'G-HB2ZWLD3CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8OBx8kQlJ1ir0FoxHykN5ydVD6meJyho',
    appId: '1:381796812762:android:fa373f83eb7f666eea62e3',
    messagingSenderId: '381796812762',
    projectId: 'new-project-f0523',
    databaseURL: 'https://new-project-f0523-default-rtdb.firebaseio.com',
    storageBucket: 'new-project-f0523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLf_Rl4Ku9EqHknUKNIIiaiSDW7tctJd8',
    appId: '1:381796812762:ios:f0cff298f94c1de8ea62e3',
    messagingSenderId: '381796812762',
    projectId: 'new-project-f0523',
    databaseURL: 'https://new-project-f0523-default-rtdb.firebaseio.com',
    storageBucket: 'new-project-f0523.appspot.com',
    iosClientId: '381796812762-nmiho4jsr7uvlvsmlu2i61j85ddq7pdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLf_Rl4Ku9EqHknUKNIIiaiSDW7tctJd8',
    appId: '1:381796812762:ios:f0cff298f94c1de8ea62e3',
    messagingSenderId: '381796812762',
    projectId: 'new-project-f0523',
    databaseURL: 'https://new-project-f0523-default-rtdb.firebaseio.com',
    storageBucket: 'new-project-f0523.appspot.com',
    iosClientId: '381796812762-nmiho4jsr7uvlvsmlu2i61j85ddq7pdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
